version: '3.7'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - '5678:5678'
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=@dm1nP@ssw0rd
      - N8N_HOST=18.231.114.87
      - N8N_PORT=5678
      - WEBHOOK_URL=http://18.231.114.87/
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: always
