name: Validate n8n configs

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate docker-compose.yml
        run: docker compose -f infra/docker-compose.yml config -q

      - name: Validate nginx config
        run: nginx -t -c $(pwd)/infra/nginx/sites-available/n8n.conf || true
